apiVersion: template.openshift.io/v1
kind: Template
message: |
  Created ${NAME} BuildConfig and ImageStream instance

metadata:
  annotations:
    openshift.io/display-name: Bookbag
    tags: gpte
    template.openshift.io/bindable: "false"
  name: bookbag-build

parameters:
  - name: NAME
    required: true
    value: bookbag-opentour-2022-dach
  - name: BUILDER_IMAGE
    required: true
    value: quay.io/openshifthomeroom/workshop-dashboard:5.0.0
  - name: GIT_REPO
    value: https://github.com/rbo/bookbag-opentour-2022-dach.git

objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${NAME}

  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:latest
      source:
        git:
          ref: master
          uri: ${GIT_REPO}
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: DockerImage
            name: ${BUILDER_IMAGE}
        type: Source
      # Manually trigger builds.
      triggers: []
